---
name: "Themerr"
guid: "e41ef0c4-c413-41ba-b4fa-8c565dc3c969"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Automatically add theme songs to movies using ThemerrDB"
description: >
  Automatically add theme songs to movies using ThemerrDB
category: "Metadata"
owner: "LizardByte"
artifacts:
  - "Jellyfin.Plugin.Themerr.dll"
# add version using CI
# add changelog using CI
