---
"base_path": "."
"base_url": "https://api.crowdin.com"  # optional (for Crowdin Enterprise only)
"preserve_hierarchy": true  # false will flatten tree on crowdin, but doesn't work with dest option
"pull_request_labels": [
  "crowdin",
  "l10n"
]

"files": [
  {
    "source": "/Locale/en.json",
    "dest": "/themerr-jellyfin.json",
    "translation": "/Locale/%two_letters_code%.%file_extension%",
    "update_option": "update_as_unapproved"
  }
]
