[project]
name = "Themerr-jellyfin"
version = "0.0.0.0"
description = "Plugin for Jellyfin that adds theme songs to movies and TV shows using ThemerrDB."
repository = "https://github.com/LizardByte/Themerr-jellyfin"
author = "LizardByte"
logo = "themerr.png"
favicon = "favicon.ico"

[build]
output = "_site"
work = ".dockle"
strict = true
clean = true

[[targets]]
name = "api"
title = "Themerr-jellyfin API"
framework = "doxygen"
source = "Jellyfin.Plugin.Themerr"
publish = false

[targets.doxygen]
inputs = ["Jellyfin.Plugin.Themerr"]
optimize_output_java = true
separate_member_pages = true
generate_xml = true

[[targets]]
name = "docs"
title = "Themerr-jellyfin documentation"
framework = "sphinx"
source = "docs/source"
home = true

[targets.sphinx]
extra_config = "docs/source/dockle_conf.py"
source_edit_link = "https://github.com/LizardByte/Themerr-jellyfin/blob/master/docs/source/{filename}"
static_paths = ["docs/source/_static"]
extra_stylesheets = [
  "https://cdn.jsdelivr.net/npm/@lizardbyte/shared-web@2026.920.12131/dist/crowdin-dockle-css.css",
]
extra_javascript = [
  "https://cdn.jsdelivr.net/npm/@lizardbyte/shared-web@2026.920.12131/dist/crowdin.js",
  "js/crowdin.js",
]
