[project]
name = "Themerr-jellyfin"
version = "0.0.0.0"
description = "Plugin for Jellyfin that adds theme songs to movies and TV shows using ThemerrDB."
repository = "https://github.com/LizardByte/Themerr-jellyfin"
author = "LizardByte"
logo = "themerr.png"
favicon = "favicon.ico"

[build]
output = "_site"
work = ".dockle"
strict = true
clean = true

[[targets]]
name = "docs"
title = "Themerr-jellyfin documentation"
framework = "sphinx"
source = "docs/source"
home = true

[targets.sphinx]
exclude_patterns = ["toc.rst"]

[[targets]]
name = "api"
title = "Themerr-jellyfin API"
framework = "doxygen"
source = "Jellyfin.Plugin.Themerr"

[targets.doxygen]
inputs = ["Jellyfin.Plugin.Themerr"]
optimize_output_java = true
separate_member_pages = true
warn_if_undoc_enum_val = false
warn_no_paramdoc = false
