# Sonar project analysis properties overrides
# Automatic analysis ignores this file, and uses .sonarcloud.properties instead

sonar.projectKey=LizardByte_Themerr-jellyfin

sonar.exclusions=third-party/**
sonar.test.exclusions=third-party/**
